/**
 * Generate human-readable reports about missing contributors.
 * This module queries merged PRs via 'gh' and produces a markdown report.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { ROOT_FOLDER } from "./constants";
import { setupGracefulShutdown } from "./utils/graceful-shutdown";

/**
 * Description placeholder
 *
 * @type {30000}
 */
const DEFAULT_CMD_TIMEOUT = 30_000; // 30s

setupGracefulShutdown("contributor-report");

/**
 * Patterns that represent generated files; contributors should not be credited
 * for these files because they are not substantive authored content.
 */
export const AUTO_GENERATED_PATTERNS = [
  "README.md",
  "README.*.md",
  "docs/README.*.md",
  "docs/*.generated.md",
];

/**
 * File globs used to infer contribution types from file paths.
 */
export const TYPE_PATTERNS = {
  agents: ["chatmodes/*.chatmode.md", "agents/*.agent.md"],
  code: ["**/*.js", "**/*.ts", "**/*.mjs", "**/*.cjs", "**/*.py"],
  doc: [
    "docs/**/*.md",
    ".github/**/*.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "LICENSE.md",
    "CHANGELOG.md",
    "*.md",
  ],
  infra: [
    ".github/workflows/**/*.yml",
    ".github/workflows/**/*.yaml",
    "**/*.yml",
    "**/*.yaml",
  ],
  instructions: ["instructions/*.instructions.md"],
  maintenance: ["package*.json", "*config*", "tsconfig*.json"],
  plugins: ["plugins/**/plugin.json"],
  skills: ["skills/"],
} as const;

/**
 * Description placeholder
 *
 * @type {*}
 */
const globCache = new Map<string, null | RegExp>();

/**
 * Convert a simple glob (with *, **) to a RegExp.
 * This is intentionally small and deterministic for our repo patterns.
 */
export const globToRegExp = (pattern: string): RegExp => {
  const DOUBLE_WILDCARD_PLACEHOLDER = "§§DOUBLE§§";

  // Escape all regex-special characters except glob wildcards (*, ?, /),
  // then translate glob syntax to regex.
  // Note: This function intentionally supports only a small subset of glob syntax.
  const regexSpecials = /[.+^${}()|[\]\\]/g;

  let normalized = String(pattern);

  // Normalize Windows-style separators to POSIX-style for matching.
  normalized = normalized.replaceAll("\\", "/");

  // Escape regex metacharacters so they are treated literally.
  normalized = normalized.replaceAll(regexSpecials, (match) => `\\${match}`);

  // Handle glob wildcards.
  normalized = normalized.replaceAll("**", DOUBLE_WILDCARD_PLACEHOLDER);
  normalized = normalized.replaceAll("*", "[^/]*");
  normalized = normalized.replaceAll(DOUBLE_WILDCARD_PLACEHOLDER, ".*");
  normalized = normalized.replaceAll("?", ".");

  return new RegExp(`^${normalized}$`);
};

/**
 * Test whether a file path matches a glob pattern.
 */
export const matchGlob = (filePath: string, pattern: string): boolean => {
  if (!globCache.has(pattern)) {
    try {
      globCache.set(pattern, globToRegExp(pattern));
    } catch {
      globCache.set(pattern, null);
    }
  }

  const regexp = globCache.get(pattern);
  if (!regexp) {
    return false;
  }

  const normalized = filePath.replaceAll("\\", "/");
  return regexp.test(normalized);
};

/**
 * Return true if the given path matches one of the known auto-generated patterns.
 */
export const isAutoGeneratedFile = (filePath: string): boolean => {
  return AUTO_GENERATED_PATTERNS.some((pattern) =>
    matchGlob(filePath, pattern),
  );
};

/**
 * Infer a contribution type string (e.g. 'skills', 'agents', 'doc') for a file path.
 * Returns null if no specific type matched.
 */
export const getFileContributionType = (filePath: string): null | string => {
  const normalized = filePath.replaceAll("\\", "/");

  for (const [type, patterns] of Object.entries(TYPE_PATTERNS)) {
    if (patterns.some((pattern) => matchGlob(normalized, pattern))) {
      return type;
    }
  }

  return null;
};

/**
 * Derive a comma-separated list of contribution type identifiers from a list of files.
 * Auto-generated files are ignored. Returns '' when no files to process.
 */
export const getContributionTypes = (files: string[]): string => {
  const types = new Set<string>();
  let processed = 0;

  for (const file of files) {
    if (isAutoGeneratedFile(file)) {
      continue;
    }

    processed += 1;
    const type = getFileContributionType(file);
    if (type) {
      types.add(type);
    }
  }

  if (processed === 0) {
    return "";
  }

  if (types.size === 0) {
    types.add("code");
  }

  return Array.from(types)
    .sort((a, b) => a.localeCompare(b))
    .join(",");
};

/**
 * Check .all-contributors output to discover missing contributors.
 * This is the canonical implementation used by contributor tooling.
 */
export const getMissingContributors = (): string[] => {
  try {
    console.log("🔍 Checking for missing contributors...");

    const configPath = path.join(process.cwd(), ".all-contributorsrc");
    const config = JSON.parse(fs.readFileSync(configPath, "utf-8")) as Record<
      string,
      unknown
    >;
    const ignoreEntries =
      (config.ignoreList as string[] | undefined) ||
      (config.ignore as string[] | undefined) ||
      [];
    const ignoreSet = new Set(
      ignoreEntries.map((entry) => entry.toLowerCase()),
    );

    if (ignoreSet.size > 0) {
      console.log(`📋 Loaded ignore list: ${Array.from(ignoreSet).join(", ")}`);
    }

    const output = execSync("npx all-contributors check", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
      timeout: DEFAULT_CMD_TIMEOUT,
    });

    // Example output line format:
    // "Missing contributors: user1, user2"
    const match = output.match(/Missing contributors:\s*(.*)/i);
    if (!match?.[1]) {
      return [];
    }

    const missing = match[1]
      .split(",")
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0)
      .filter((entry) => !ignoreSet.has(entry.toLowerCase()));

    return missing;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`Warning: Failed to get missing contributors: ${message}`);
    return [];
  }
};

/**
 * Description placeholder
 *
 * @interface PullRequest
 * @typedef {PullRequest}
 */
interface PullRequest {
  /**
   * Description placeholder
   *
   * @type {number}
   */
  number: number;
  /**
   * Description placeholder
   *
   * @type {string}
   */
  title: string;
  /**
   * Description placeholder
   *
   * @type {string}
   */
  author: string;
  /**
   * Description placeholder
   *
   * @type {string[]}
   */
  files: string[];
}

/**
 * Description placeholder
 *
 * @export
 * @interface ContributorPullRequest
 * @typedef {ContributorPullRequest}
 */
export interface ContributorPullRequest {
  /**
   * Description placeholder
   *
   * @type {number}
   */
  number: number;
  /**
   * Description placeholder
   *
   * @type {string}
   */
  title: string;
  /**
   * Description placeholder
   *
   * @type {string[]}
   */
  files: string[];
}

/**
 * Description placeholder
 *
 * @returns {PullRequest[]}
 */
function getMergedPullRequests(): PullRequest[] {
  const ghPath = "gh";
  const query =
    "query($after: String) {\n" +
    '  repository(owner: "github", name: "awesome-copilot") {\n' +
    "    pullRequests(first: 100, states: MERGED, orderBy: {field: UPDATED_AT, direction: DESC}, after: $after) {\n" +
    "      nodes {\n" +
    "        number\n" +
    "        title\n" +
    "        author { login }\n" +
    "        files(first: 100) { nodes { path } }\n" +
    "      }\n" +
    "      pageInfo { hasNextPage endCursor }\n" +
    "    }\n" +
    "  }\n" +
    "}";

  let after: null | string = null;
  const prs: PullRequest[] = [];

  while (true) {
    const args = [
      "api",
      "graphql",
      "-f",
      `query=${query}`,
      "-f",
      `after=${after ?? ""}`,
    ];

    const output = execSync(`${ghPath} ${args.join(" ")}`, {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
      timeout: DEFAULT_CMD_TIMEOUT,
    });

    const json = JSON.parse(output) as Record<string, unknown>;
    const repository = (json.data as Record<string, unknown>)?.repository as
      | Record<string, unknown>
      | undefined;
    const pullRequests = repository?.pullRequests as
      | Record<string, unknown>
      | undefined;
    const nodes = (pullRequests?.nodes as Record<string, unknown>[]) || [];

    for (const pr of nodes) {
      const author = pr.author as null | Record<string, unknown>;
      const prFiles = pr.files as { nodes?: { path: string }[] } | undefined;
      prs.push({
        author: typeof author?.login === "string" ? author.login : "unknown",
        files: Array.isArray(prFiles?.nodes)
          ? prFiles.nodes.map((node) => String(node.path))
          : [],
        number: Number(pr.number),
        title: String(pr.title),
      });
    }

    const pageInfo = pullRequests?.pageInfo as
      | Record<string, unknown>
      | undefined;
    const hasNextPage = Boolean(pageInfo?.hasNextPage);
    const endCursor =
      typeof pageInfo?.endCursor === "string" ? pageInfo.endCursor : null;
    if (!hasNextPage || !endCursor) {
      break;
    }
    after = endCursor;
  }

  return prs;
}

/**
 * Description placeholder
 *
 * @export
 * @param {string} username
 * @param {{ includeAllFiles?: boolean }} [options={}]
 * @returns {ContributorPullRequest[]}
 */
export function fetchContributorMergedPrs(
  username: string,
  options: { includeAllFiles?: boolean } = {},
): ContributorPullRequest[] {
  const prs = getMergedPullRequests().filter(
    (pr) => pr.author.toLowerCase() === username.toLowerCase(),
  );
  if (options.includeAllFiles) {
    return prs.map((pr) => ({
      files: pr.files,
      number: pr.number,
      title: pr.title,
    }));
  }

  return prs.map((pr) => ({
    files: [],
    number: pr.number,
    title: pr.title,
  }));
}

/**
 * Description placeholder
 *
 * @param {string[]} missingContributors
 * @returns {string}
 */
function generateReport(missingContributors: string[]): string {
  if (missingContributors.length === 0) {
    return "✅ No missing contributors found.";
  }

  const prs = getMergedPullRequests();

  const matched: { pr: PullRequest; types: string }[] = [];
  for (const pr of prs) {
    if (!missingContributors.includes(pr.author)) {
      continue;
    }
    const types = getContributionTypes(pr.files);
    matched.push({ pr, types });
  }

  const lines = [
    "# Missing Contributors Report",
    "",
    "The following merged PRs appear to include contributions from users that are missing from the contributors list.",
    "",
    "## PRs",
    "",
  ];

  for (const match of matched) {
    const types = match.types ? ` (${match.types})` : "";
    lines.push(
      `- #${match.pr.number} ${match.pr.title} (@${match.pr.author})${types}`,
    );
  }

  lines.push("");
  lines.push("## Next step");
  lines.push("");
  lines.push(
    `npx all-contributors add ${missingContributors.join(" ")} --multiple`,
  );

  return lines.join("\n");
}

/** Description placeholder */
function main(): void {
  const missing = getMissingContributors();
  const report = generateReport(missing);
  const reportPath = path.join(ROOT_FOLDER, "reports", "contributor-report.md");

  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, report, "utf-8");

  console.log("\n✅ Contributor report generated:", reportPath);
}

main();
