#!/usr/bin/env tsx
import { spawnSync } from "child_process";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import readline from "readline";

interface Catalog {
  generatedAt?: string;
  mcpServers: string[];
}

const argv = process.argv.slice(2);
const flags = new Set<string>(
  argv.filter((s) => s.startsWith("--")).map((s) => s.replace(/^--/, "")),
);
const getArg = (name: string) => {
  const idx = argv.findIndex((a) => a === `--${name}`);
  if (idx >= 0 && idx + 1 < argv.length) return argv[idx + 1];
  return undefined;
};

const DRY_RUN = !flags.has("apply");
const PRUNE = flags.has("prune");
const FORCE = flags.has("force");
const HELPERS_DIR =
  getArg("helpers-dir") || path.join("scripts", "mcp-helpers");
const CATALOG_PATH =
  getArg("catalog-path") || path.join(".opencode", "mcp_servers.json");
const OPENCODE_PATH = getArg("opencode-path") || "opencode.json";

function readCatalog(p: string): Catalog {
  if (!fs.existsSync(p)) return { mcpServers: [] };
  const raw = fs.readFileSync(p, "utf8");
  try {
    const parsed = JSON.parse(raw) as Catalog;
    return parsed;
  } catch (err) {
    console.error(`Failed to parse catalog ${p}:`, err);
    process.exit(2);
  }
}

function writeBackup(p: string) {
  if (!fs.existsSync(p)) return;
  const ts = new Date().toISOString().replaceAll(/[:.]/g, "-");
  const bak = `${p}.bak.${ts}`;
  fs.copyFileSync(p, bak);
  console.info(`Backup written: ${bak}`);
}

function writeJSON(p: string, obj: unknown, dry = true) {
  const data = JSON.stringify(obj, null, 2) + "\n";
  if (dry) {
    console.info(`[dry-run] would write ${p}`);
    return;
  }
  writeBackup(p);
  fs.writeFileSync(p, data, "utf8");
  console.info(`Wrote ${p}`);
}

function parseDockerOutput(output: string): string[] {
  const lines = output
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const servers = new Set<string>();
  // Flexible parsing: look for tokens that look like names (alphanumeric, dashes, underscores)
  for (const line of lines) {
    // common formats: "NAME: server-name", "server-name (running)", plain list
    const nameMatch = line.match(/([\w-]{3,100})/);
    if (nameMatch) servers.add(nameMatch[1]);
  }
  return Array.from(servers).sort();
}

function generateHelperContent(server: string, catalogPath: string) {
  return `/* AUTO-GENERATED by scripts/mcp-runner.ts */\n// Source catalog: ${catalogPath}\n\nexport async function connect() {\n  return {\n    server: "${server}",\n    async healthCheck() {\n      return { ok: true, server: '${server}' };\n    }\n  };\n}\n`;
}

function checksum(s: string) {
  return crypto.createHash("sha256").update(s).digest("hex");
}

function ensureHelpersDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function generateHelpers(
  servers: string[],
  dir: string,
  catalogPath: string,
  dry = true,
) {
  ensureHelpersDir(dir);
  const backupsDir = path.join(dir, "backups");
  if (!fs.existsSync(backupsDir)) fs.mkdirSync(backupsDir, { recursive: true });

  for (const s of servers) {
    const file = path.join(dir, `${s}.ts`);
    const content = generateHelperContent(s, catalogPath);
    let write = true;
    if (fs.existsSync(file)) {
      const existing = fs.readFileSync(file, "utf8");
      if (checksum(existing) === checksum(content)) {
        console.info(`No change for helper ${file}`);
        write = false;
      } else {
        const ts = new Date().toISOString().replaceAll(/[:.]/g, "-");
        const bak = path.join(backupsDir, `${s}.ts.bak.${ts}`);
        if (!dry) fs.copyFileSync(file, bak);
        console.info(`Existing helper backed up: ${bak}`);
      }
    }
    if (write) {
      if (dry) {
        console.info(`[dry-run] would write helper ${file}`);
      } else {
        fs.writeFileSync(file, content, "utf8");
        console.info(`Wrote helper ${file}`);
      }
    }
  }
}

function discoverDockerServers(): string[] {
  // Try the recommended command first
  const cmd = "docker";
  const args = ["mcp", "gateway", "run", "--profile", "adminbot"];
  try {
    const out = spawnSync(cmd, args, { encoding: "utf8" });
    if (out.error) throw out.error;
    if (out.status !== 0) {
      console.warn(
        "docker mcp command exited non-zero, falling back to docker ps",
      );
      return discoverViaDockerPs();
    }
    return parseDockerOutput(out.stdout || out.stderr || "");
  } catch (err) {
    console.warn(
      "Failed to run docker mcp gateway run — falling back to docker ps",
      err,
    );
    return discoverViaDockerPs();
  }
}

function discoverViaDockerPs(): string[] {
  const out = spawnSync(
    "docker",
    ["ps", "--format", "{{.Names}}\t{{.Image}}"],
    { encoding: "utf8" },
  );
  if (out.error) {
    console.error("Failed to run docker ps:", out.error);
    return [];
  }
  const lines = (out.stdout || "")
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const names = lines.map((l) => l.split(/\t/)[0]).filter(Boolean);
  return names.sort();
}

async function main() {
  console.info(
    `mcp-runner --dry-run=${DRY_RUN} --prune=${PRUNE} --force=${FORCE}`,
  );
  const catalog = readCatalog(CATALOG_PATH);
  console.info(`Read catalog with ${catalog.mcpServers.length} servers`);

  const dockerServers = discoverDockerServers();
  console.info(`Discovered ${dockerServers.length} docker servers`);

  // Merge: auto-add new docker servers to catalog (in-memory)
  const merged = new Set<string>(catalog.mcpServers || []);
  for (const s of dockerServers) merged.add(s);
  const mergedArr = Array.from(merged).sort();

  const toAdd = mergedArr.filter((s) => !catalog.mcpServers.includes(s));
  const catalogedNotRunning = catalog.mcpServers.filter(
    (s) => !dockerServers.includes(s),
  );

  console.info(`New servers to add: ${toAdd.length}`);
  if (toAdd.length > 0) console.info(toAdd.join(", "));
  if (!DRY_RUN && toAdd.length > 0) {
    catalog.mcpServers = mergedArr;
    catalog.generatedAt = new Date().toISOString();
    writeJSON(CATALOG_PATH, catalog, false);
  } else if (DRY_RUN && toAdd.length > 0) {
    console.info(
      `[dry-run] would update ${CATALOG_PATH} with ${toAdd.length} new servers`,
    );
  }

  console.info(`Cataloged but not running: ${catalogedNotRunning.length}`);
  if (catalogedNotRunning.length > 0)
    console.info(catalogedNotRunning.join(", "));

  // Generate helpers for merged catalog
  generateHelpers(mergedArr, HELPERS_DIR, CATALOG_PATH, DRY_RUN);

  // Update opencode.json mcpServers field by merging
  if (fs.existsSync(OPENCODE_PATH)) {
    try {
      const raw = fs.readFileSync(OPENCODE_PATH, "utf8");
      const parsed = JSON.parse(raw);
      // Try a couple of common shapes
      if (Array.isArray(parsed.mcpServers)) {
        if (DRY_RUN)
          console.info(`[dry-run] would update ${OPENCODE_PATH}.mcpServers`);
        else {
          writeBackup(OPENCODE_PATH);
          parsed.mcpServers = mergedArr;
          fs.writeFileSync(
            OPENCODE_PATH,
            JSON.stringify(parsed, null, 2) + "\n",
            "utf8",
          );
          console.info(`Updated ${OPENCODE_PATH}.mcpServers`);
        }
      } else if (parsed.opencode && Array.isArray(parsed.opencode.mcpServers)) {
        if (DRY_RUN)
          console.info(
            `[dry-run] would update ${OPENCODE_PATH}.opencode.mcpServers`,
          );
        else {
          writeBackup(OPENCODE_PATH);
          parsed.opencode.mcpServers = mergedArr;
          fs.writeFileSync(
            OPENCODE_PATH,
            JSON.stringify(parsed, null, 2) + "\n",
            "utf8",
          );
          console.info(`Updated ${OPENCODE_PATH}.opencode.mcpServers`);
        }
      } else {
        console.info(`No mcpServers field found in ${OPENCODE_PATH}; skipping`);
      }
    } catch (err) {
      console.error(`Failed to read/parse ${OPENCODE_PATH}:`, err);
    }
  }

  // Prune: remove docker servers not in catalog — only if prune flag set
  if (PRUNE) {
    const toRemove = dockerServers.filter((s) => !mergedArr.includes(s));
    if (toRemove.length === 0) {
      console.info("No docker servers to prune");
    } else {
      console.info(`Docker servers to remove: ${toRemove.join(", ")}`);
      if (DRY_RUN) {
        console.info(`[dry-run] would remove ${toRemove.length} containers`);
      } else {
        // interactive confirmation required
        const prompt = `Are you sure you want to remove ${toRemove.length} containers? Type REMOVE to confirm:`;
        const input = readline.createInterface({
          input: process.stdin,
          output: process.stdout,
        });
        input.question(prompt + " ", (answer: string) => {
          input.close();
          if (answer !== "REMOVE") {
            console.info("Aborted by user");
            process.exit(5);
          }
          for (const c of toRemove) {
            console.info(`Stopping and removing ${c}`);
            const stop = spawnSync("docker", ["stop", c], { encoding: "utf8" });
            console.info(stop.stdout || stop.stderr || "");
            const rm = spawnSync("docker", ["rm", c], { encoding: "utf8" });
            console.info(rm.stdout || rm.stderr || "");
          }
        });
      }
    }
  }

  console.info("Done");
}

main().catch((err) => {
  console.error(err);
  process.exit(4);
});
