import crypto from "crypto";
import fs from "fs";

export function parseDockerOutput(output: string): string[] {
  const lines = output
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const servers = new Set<string>();
  for (const line of lines) {
    // Prefer extracting full tokens separated by whitespace or tabs
    const parts = line
      .split(/\s+|\t+/)
      .map((p) => p.trim())
      .filter(Boolean);
    if (parts.length > 0) {
      // For docker ps-like output the first token is usually the container name
      const token = parts[0];
      const nameMatch = token.match(/^([\w-]{3,100})$/);
      if (nameMatch) servers.add(nameMatch[1]);
      else {
        // fallback: extract first suitable chunk from the whole line
        const fallback = line.match(/([\w-]{3,100})/);
        if (fallback) servers.add(fallback[1]);
      }
    }
  }
  return Array.from(servers).sort();
}

export function generateHelperContent(server: string, catalogPath: string) {
  return `/* AUTO-GENERATED by scripts/mcp-runner.ts */\n// Source catalog: ${catalogPath}\n\nexport async function connect() {\n  return {\n    server: "${server}",\n    async healthCheck() {\n      return { ok: true, server: '${server}' };\n    }\n  };\n}\n`;
}

export function checksum(s: string) {
  return crypto.createHash("sha256").update(s).digest("hex");
}

export function ensureHelpersDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}
